substitutions:
  # See if this is either a tag or a PR
  # Replace "/" in branch names with "-"
  _TAG_NAME: ${TAG_NAME:-${_HEAD_BRANCH/\//-}}
  # Capture long and short versions of the repository name
  _REPO_LONG: ${REPO_NAME#*/}
  _REPO_SHORT: ${REPO_NAME#*-}
  # If it's a PR, image tag will be the Head Branch
  # If it's a tag, image tag will be the tag
  # If it's not a tag or a PR, then it should be latest
  _IMAGE_NAME: ${_REPO_SHORT}:${_TAG_NAME:-latest}
  # Test payloads
  _URL: $(body.repository.html_url)
steps:
- name: gcr.io/$PROJECT_ID/project-version
  id: version
  args:
   - $REPO_NAME
   - $BRANCH_NAME
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  id: build
  args:
    - --destination=gcr.io/$PROJECT_ID/$_IMAGE_NAME
    - --cache=true
    - --cache-ttl=48h
    - --single-snapshot
    - --context=./
  waitFor:
    - version
- name: 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
  id: test
  entrypoint: bash
  args:
    - '-cx'
    - |
       entrypoint.sh $REPO_NAME $BRANCH_NAME \
       && cat stepvars/tag \
       && cat stepvars/version \
       && cat gradle.properties \
       || exit 1
  waitFor:
    - build
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: tag-image
  entrypoint: bash
  args:
   - '-cx'
   - |
      if [ $BRANCH_NAME == "master" ]
      then
        gcloud container images add-tag gcr.io/$PROJECT_ID/${_IMAGE_NAME} gcr.io/$PROJECT_ID/$_REPO_SHORT:`<stepvars/version`
      fi
  waitFor:
    - test
- name: gcr.io/$PROJECT_ID/gh
  id: delete-release
  entrypoint: bash
  args:
   - '-cx'
   - |
      if [ $BRANCH_NAME == "master" ]
      then
        gh release delete `<stepvars/tag` || exit 0
      fi
  waitFor:
    - test
- name: gcr.io/$PROJECT_ID/gh
  id: create-release
  entrypoint: bash
  args:
   - '-cx'
   - |
      if [ $BRANCH_NAME == "master" ]
      then
        gh release create `<stepvars/tag` --target master
      fi
  waitFor:
    - delete-release
timeout: 3600s
options:
  dynamic_substitutions: true
  env:
    - GITHUB_TOKEN=$_GITHUB_TOKEN
